version: '3'
services:
  micro-service:
    image: micro-service
    build: ./micro-service
    ports:
      - "3333:8080"
    environment:
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224
    networks:
      - microservice-network
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
#    ports:
#      - "9200:9200"
#    networks:
#      - elasticsearch
#    expose:
#      - "9200"
#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.3.2
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#    ports:
#      - "5601:5601"
#    networks:
#      - elasticsearch
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - microservice-network

networks:
  microservice-network: